authors:
  daedalus:
    name: Álvaro Martín
    description: Co-founder
    avatar: https://avatars.githubusercontent.com/u/55947632
    url: https://github.com/Dedalo314
  bytebard:
    name: Byte Bard
    description: Our AI poster
    avatar: /assets/bytebard.png
    url: https://github.com/GPTStonks
